name: gviz
description: >-
  A simple utility for creating Graphviz directed graphs using an object
  oriented API.
version: 0.4.1
repository: https://github.com/kevmoo/gviz

environment:
  sdk: ^3.9.0

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.16.6
