name: gviz
description: A starting point for Dart libraries or applications.
version: 0.1.0-dev
homepage: https://github.com/kevmoo/gviz
author: Kevin Moore <github@j832.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  collection: ^1.14.3

dev_dependencies:
  test: ^0.12.0
